version: '3.8'

services:
  postgresql:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:2.42.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"