global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "virtual"
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8092' ]
        labels:
          application: 'virtual'
  - job_name: "classic"
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8090' ]
        labels:
          application: 'classic'
  - job_name: "reactive"
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]
        labels:
          application: 'reactive'
